name: action_checker_weekly
on:
  # 手動実行できるようにする！
  workflow_dispatch:
  schedule:
    # 日本時間9時00分
    - cron: '0 0 * * *'

jobs:
  checker:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./action_checker/
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # pip更新
          pip install -r requirements.txt

      - name: Run script
        run: |
          python weekly.py \
            "${{ secrets.LINE_NOTIFY_TOKEN }}" \
            "${{ secrets.CHECK_USERS }}"

      - name: Run script for server-side kotlin
        run: |
          python weekly.py \
            "${{ secrets.LINE_NOTIFY_TOKEN_TO_SERVER_SIDE_KOTLIN }}" \
            "${{ secrets.CHECK_USERS_SERVER_SIDE_KOTLIN }}"

      - name: Report if checker hadn't worked.
        if: failure()
        run: |
          curl -X POST \
            -H 'Authorization: Bearer ${{ secrets.LINE_NOTIFY_TOKEN }}' \
            -F "message=contributionsの確認が正常に行えませんでした..." \
            'https://notify-api.line.me/api/notify'
          curl -X POST \
            -H 'Authorization: Bearer ${{ secrets.LINE_NOTIFY_TOKEN_TO_SERVER_SIDE_KOTLIN }}' \
            -F "message=contributionsの確認が正常に行えませんでした..." \
            'https://notify-api.line.me/api/notify'
