name: url_watcher_odhackathon

on:
  workflow_dispatch:
  schedule:
    # 日本時間23時00分
    - cron: "0 14 * * *"

jobs:
  checker:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./url_watcher/odhackathon/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Diff check
        id: diff-check
        uses: kokoichi206/action-URL-watcher@main
        with:
          url: https://odhackathon.metro.tokyo.lg.jp/
          excluded-patterns: 'style.min.css\?[0-9]*-[0-9]*;common.js\?[0-9]*-[0-9]*'
          save-dir: ./url_watcher/odhackathon
          save-file: index.txt

      - name: Notify if diff found
        if: ${{ steps.diff-check.outputs.diff == true }}
        run: |
          # Slack API を使って通知
          ## see: https://api.slack.com/methods/chat.postMessage
          curl -X POST 'https://slack.com/api/chat.postMessage' \
            -d "token=${{ secrets.SLACK_API_TOKEN_HACKATHON }}" \
            -d 'channel=#times_tominaga' \
            -d 'text=HPの更新を検知しました。 https://github.com/kokoichi206/routines/commits/main'
