name: url_watcher_odhackathon

on:
  workflow_dispatch:
  schedule:
    # 日本時間23時00分
    - cron: "0 14 * * *"

jobs:
  checker:
    runs-on: ubuntu-latest
    environment: production
    env:
      NEW_FILE_NAME: latest.txt
      OLD_FILE_NAME: index.txt
    defaults:
      run:
        shell: bash
        working-directory: ./url_watcher/odhackathon/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Diff check
        id: diff-check
        run: |
          curl https://odhackathon.metro.tokyo.lg.jp/ > "${NEW_FILE_NAME}"
          # 以下のパターンは更新検知の対象から削除する。
          excluded_patterns=("style.min.css\?[0-9]*-[0-9]*" "common.js\?[0-9]*-[0-9]*")

          for pattern in "${excluded_patterns[@]}"; do
            echo "$pattern"
            # Delete the specified pattern
            sed -i -E "s@$pattern@@g" "${NEW_FILE_NAME}"
            sed -i -E "s@$pattern@@g" "${OLD_FILE_NAME}"
          done
          set +e
          diff "${NEW_FILE_NAME}" "${OLD_FILE_NAME}"
          STATUS_CODE=$?
          set -e
          result=false
          if [ "${STATUS_CODE}" -gt 0 ]; then
            result=true
          fi
          echo "::set-output name=diff::$(echo ${result})"

      - name: Commit and push if diff found
        if: ${{ steps.diff-check.outputs.diff }}
        run: |
          mv "${NEW_FILE_NAME}" "${OLD_FILE_NAME}"
          git config user.name kokoichi206
          git config user.email tt.300607@gmail.com
          git add "${OLD_FILE_NAME}"
          # 複数行のコミットメッセージ
          git commit -F- << EOS
          $(date +%m-%d)更新分

          * 監視対象: https://odhackathon.metro.tokyo.lg.jp/
          EOS

          git push
          git log

      - name: Notify if diff found
        if: ${{ steps.diff-check.outputs.diff }}
        run: |
          # Slack API を使って通知
          ## see: https://api.slack.com/methods/chat.postMessage
          curl -X POST 'https://slack.com/api/chat.postMessage' \
            -d "token=${{ secrets.SLACK_API_TOKEN_HACKATHON }}" \
            -d 'channel=#times_tominaga' \
            -d 'text=HPの更新を検知しました。 https://github.com/kokoichi206/routines/commits/main'
